# Generated by Django 4.2.3 on 2023-07-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Redmi', 'Redmi'), ('Oneplus', 'Oneplus'), ('Realme', 'Realme')], max_length=100, null=True),
        ),
    ]
